force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>Gifts represent donations of money, stock, or other value that are tied to specific individuals, households, or organizations.</description>
    <label>Gift</label>
    <nameField>
        <displayFormat>Gift-{0000}</displayFormat>
        <label>Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Date__c.field-meta.xml
<CustomField>
    <fullName>Gift_Date__c</fullName>
    <description>This is the date when the gift was received. On a check, this would be the check date, or with an Electronic Fund Transfer, this would be the date the EFT hit the bank.</description>
    <label>Gift Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift_GiftMembershipRelationship__c/Gift_GiftMembershipRelationship__c.object-meta.xml
<CustomObject>
    <description>This Junction Object represents the link between a membership and the gifts that paid for it.</description>
    <label>Sponsoring Gift</label>
    <nameField>
        <displayFormat>SG-GM-{00000}</displayFormat>
        <label>Sponsoring Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsoring Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift_GiftMembershipRelationship__c/fields/Gift__c.field-meta.xml
<CustomField>
    <fullName>Gift__c</fullName>
    <description>This field represents the gift sponsoring the membership on the other end of this Junction Object.</description>
    <label>Gift</label>
    <referenceTo>Gift__c</referenceTo>
    <relationshipName>Sponsoring_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gift_GiftMembershipRelationship__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>This field captures the membership that was paid for by the gift on the other side of this Junction Object.</description>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Sponsoring_Gifts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Memberships are tied to specific individuals, households, or organizations.</description>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>This field represents this membership's official expiration date.</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field represents the start date of this membership (rather than when this membership record was created).</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateMembershipDates.cls
public class UpdateMembershipDates {

    
    /**
     * This routine gets the extended set of gifts related to a given membership_id
     * 
     * @param Id membership_id the membership id to get gifts for
     * @return List<Gift__c> the set of `Gift__c`s to related to this membership through a Gift_GMR junction record.
	 */
    public static List<Gift__c> getGiftSetForMembership( Id membership_id ) {
        return [select Id, Gift_Date__c from Gift__c where Id in (select Gift__c from Gift_GiftMembershipRelationship__c where Membership__c = :membership_id )];
    }
    
    
    /**
     * This routine updates the expiration date of a given membership
     * based on the Gift Date of the latest gift associated with the
     * given membership.
     * 
     * @param List<Gift_GiftMembershipRelationship__c> links the Junction Object link between the membership and the gift
     * 
     **/
    public static void updateMembershipExpirationDate( List<Gift_GiftMembershipRelationship__c> links ) {
        
        for ( Gift_GiftMembershipRelationship__c link : links ) {
            
            Membership__c membership = new Membership__c(id=link.Membership__c);
            
            List<Gift__c> gifts = getGiftSetForMembership( membership.Id );
            
            // We know that there is at least one such, 
            // because we encountered this membership 
            // through a gift relation.
            Date endDate = Date.valueOf( ((Gift__c) gifts.remove(0)).Gift_Date__c ).addYears( 1 );
         	 
            for ( Gift__c gift : gifts ) {
                
                Date possibleEndDate = Date.valueOf( gift.Gift_Date__c ).addYears( 1 );
                
                if ( endDate < possibleEndDate ) {
                    
                    endDate = possibleEndDate;
                    
                }
                
            }
            
            membership.Expiration_Date__c = endDate;
            
            update membership;
                  
        }
        

        /**
        Membership__c membership = [select Id, Expiration_Date__c from Membership__c where Id = :link.Membership__c];
       
        Date giftDate = Date.valueOf([select Gift_Date__c from Gift__c where ID = :link.Gift__c LIMIT 1].Gift_Date__c); 
        
        Date candidateExpirationDate = giftDate.addYears( 1 );
        
        if ( Date.valueOf( membership.Expiration_Date__c ) < candidateExpirationDate ) {
            
            membership.Expiration_Date__c = candidateExpirationDate;

			update membership;  
            
        } 
		*/
        
    }

    
	/**
     * This routine updates the start date of a given membership
     * based on the Gift Date of the earliest gift associated with the
     * given membership.
     * 
     * @param List<Gift_GiftMembershipRelationship__c> links the Junction Object link between the membership and the gift
     * 
     **/    
    public static void updateMembershipStartDate( List<Gift_GiftMembershipRelationship__c> links ) {
        
        for ( Gift_GiftMembershipRelationship__c link : links ) {
            
            Membership__c membership = new Membership__c(id=link.Membership__c);
            
            List<Gift__c> gifts = getGiftSetForMembership( membership.Id );
            
            // We know that there is at least one such, 
            // because we encountered this membership 
            // through a gift relation.
            Date startDate = ((Gift__c) gifts.remove(0)).Gift_Date__c;
            
            for ( Gift__c gift : getGiftSetForMembership( membership.Id ) ) {
                
                if ( startDate > gift.Gift_Date__c ) {
                    
                    startDate = gift.Gift_Date__c;
                    
                }
                
            }
            
            membership.Start_Date__c = startDate;
            
            update membership;
            
        }
        
        /*
        Date giftDate = Date.valueOf([select Gift_Date__c from Gift__c where ID = :link.Gift__c LIMIT 1].Gift_Date__c);
        Membership__c membership = [select Id, Start_Date__c from Membership__c where Id = :link.Membership__c];
        
        System.debug( 'Gift Date: ' + giftDate );
        System.debug( 'Membership Start Date: ' + membership.Start_Date__c );
        
        if ( membership.Start_Date__c > giftDate || membership.Start_Date__c == null ) {
            
            membership.Start_Date__c = giftDate;
            
            update membership;
            
        } 
		*/
        
    }
}